service: sls-add-file-in-s3
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  timeout: 30
  stage: ${opt:stage, 'dev'}
  memorySize: 1024
  environment:
    DISTRIBUITED_GENERATION_BUCKET: ${env:DISTRIBUITED_GENERATION_BUCKET}
    ROLLBAR_ACCESS_TOKEN: ${env:ROLLBAR_ACCESS_TOKEN}
    ROLLBAR_ENVIRONMENT: ${env:ROLLBAR_ENVIRONMENT}
  apiGateway:
    apiKeys:
      - name: sls-s3-document-uploader-api-key
    usagePlan:
      throttle:
        burstLimit: 200
        rateLimit: 100
    binaryMediaTypes:
      - '*/*'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource: arn:aws:s3:::${env:DISTRIBUITED_GENERATION_BUCKET}/*

functions:
  app:
    handler: src/app.handler
    events:
      - http:
          path: billing/upload-proof
          method: post
          private: true
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    printOutput: true

package:
  individually: true